print('running init.lua')
tilemap = tilemap_load('res/maps/untitled.lua')
for i = 1,10 do
    entity = Entity:new()
    entity:set_pos(math.random(0, 31) * 16, math.random(0, 31) * 16)
    entity:set_vel(math.random(-1, 1), math.random(-1, 1))
    entity:set_size(16, 18)
    entity:set_sprite('res/player1.bmp')
    entity:add_frame(ACTION_WALKING, DIRECTION_UP, 0)
    entity:add_frame(ACTION_STANDING, DIRECTION_UP, 1)
    entity:add_frame(ACTION_WALKING, DIRECTION_UP, 2)
    entity:add_frame(ACTION_WALKING, DIRECTION_RIGHT, 3)
    entity:add_frame(ACTION_STANDING, DIRECTION_RIGHT, 4)
    entity:add_frame(ACTION_WALKING, DIRECTION_RIGHT, 5)
    entity:add_frame(ACTION_WALKING, DIRECTION_DOWN, 6)
    entity:add_frame(ACTION_STANDING, DIRECTION_DOWN, 7)
    entity:add_frame(ACTION_WALKING, DIRECTION_DOWN, 8)
    entity:add_frame(ACTION_WALKING, DIRECTION_LEFT, 9)
    entity:add_frame(ACTION_STANDING, DIRECTION_LEFT, 10)
    entity:add_frame(ACTION_WALKING, DIRECTION_LEFT, 11)
end
print('init.lua exited cleanly')
