#!/bin/sh
# indent.sh: A little something something to make everybody's life easier :-)
# Explanation of switches:
# -kr	K&R-style
# -brf	Put braces on function definition line.
# -ts4	Four space indent.
# -nut  Spaces instead of tabs.
indent -kr -brf -ts4 -nut "$@"
