#!/usr/bin/env python

"""
Converts .tmx file to a C-friendly binary format.
"""

import array
import base64
import struct
import sys
import xml.dom.minidom
import zlib

for fname in sys.argv[1:]:
    outfile = open(fname + '.bin', 'wb')
    document = xml.dom.minidom.parse(fname)
    map_ = document.getElementsByTagName('map')[0]
    image = document.getElementsByTagName('image')[0]
    layers = document.getElementsByTagName('data')
    source = str(image.getAttribute('source'))
    width = int(map_.getAttribute('width'))
    height = int(map_.getAttribute('height'))
    depth = len(layers)
    outfile.write(array.array('c', source + '\0'))
    outfile.write(struct.pack('iii', width, height, depth))
    for layer in layers:
        data = zlib.decompress(base64.b64decode(layer.childNodes[0].data))
        outfile.write(array.array('l', data))
    outfile.close()
